GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2hvaSIsImlhdCI6MTYzOTk4NDk2NiwiZXhwIjoxNjM5OTg0OTk2fQ.TWPpzQkzVB6Ecuryn2T47ufLE1t4VhHWV9_GHTCYfPI

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2hvaSIsImlhdCI6MTYzOTg5NjU2NH0.gFr0GvwE-aUFYsuTIn2zljFsYq8yiL1jGuV2KszoK30"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Choi"
}